import os
from app import get_live_jobs, grade_job_with_ai, send_email
from dotenv import load_dotenv

# Load credentials from .env (locally) or GitHub Secrets (in the cloud)
load_dotenv()

def run_daily_scan():
    print("🚀 Autopilot: Starting Daily Executive Scan at 5:00 AM EST...")
    
    # --- CONFIGURATION ---
    # These match Steve's specific executive requirements
    target_title = "Strategic Account Executive"
    dealbreakers = "100% Remote, Must allow work from Kenya, No micromanagement."
    industry_keywords = "B2B Sales, SaaS, Hospitality"
    target_ote = 0  # Set to 0 for 'Any' so we don't filter out good opportunities
    contact_email = os.getenv("EMAIL_SENDER")

    # 1. Scrape 20 jobs (Quota Pull)
    print(f"📡 Searching the market for {target_title} roles...")
    raw_jobs = get_live_jobs(target_title, limit=20)
    
    valid_matches = []

    # 2. Grade and Filter using the AI Executive Rubric
    for job in raw_jobs:
        title = job.get('title', 'Unknown Title')
        company = job.get('company_name', 'Unknown Company')
        
        # This calls the Gemini logic we built in app.py
        ai_summary = grade_job_with_ai(job, dealbreakers, target_ote, industry_keywords)
        
        if ai_summary and not ai_summary.startswith("FAIL"):
            print(f"✅ Match Found: {title} @ {company}")
            apply_link = job.get('apply_options', [{}])[0].get('link', '#')
            
            # Format the match for the HTML email
            match_html = f"""
            <div style="border-bottom: 1px solid #ddd; padding-bottom: 20px;">
                <h3 style="color: #2E86C1;">{title} @ {company}</h3>
                {ai_summary.replace('\n', '<br>')}
                <br><br>
                <a href="{apply_link}" style="background-color: #28B463; color: white; padding: 10px 15px; text-decoration: none; border-radius: 5px;"><b>Apply Now</b></a>
            </div>
            """
            valid_matches.append(match_html)
        else:
            reason = ai_summary.replace("FAIL -", "") if ai_summary else "No data"
            print(f"❌ Skipped {title}: {reason}")

    # 3. Final Dispatch: Send the morning briefing
    if valid_matches:
        print(f"🎯 Found {len(valid_matches)} elite matches! Dispatching email...")
        html_report = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2>🌅 Steve's Morning Executive Brief</h2>
            <p>The AI Agent scanned the market at 5:00 AM EST and found these high-trust roles:</p>
            <hr>
            {"".join(valid_matches)}
            <br>
            <p><i>Generated by your Personal AI Agent.</i></p>
        </body>
        </html>
        """
        success = send_email(contact_email, "🌅 Your 5:00 AM Executive Job Brief", html_report)
        if success:
            print("📧 Email sent successfully.")
    else:
        print("🛡️ Scan complete. No jobs met the 5-star criteria this morning.")

if __name__ == "__main__":
    run_daily_scan()